server:
  port: 6080

---
spring:
  application:
    name: id-generator

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idgenerator
    username: root
    password: root

#---
#spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379

---
id:
  generator:
    one-request-num-max: 50
    dashboard: http://127.0.0.1:6082